[package]
name = "wasmtime-dbg"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wasmtime-dbg"
path = "main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "15"
