[package]
name = "wasmtime-dbg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nothing = "0.1.12"
wasmtime = { version = "8.0.1", features = ["cache","cranelift","jitdump","parallel-compilation","pooling-allocator"] }
